name: BTE-TokenSystem
version: '${project.version}'
main: de.cookiemc.btetokensystem.BTETokenSystem
authors: [ CookieMC337 ]
description: BTE-PS Token System
commands:
  addshoptoken:
    permission: btetoken.addshoptoken
  addtoken:
    permission: btetoken.add
    description: Usern Token adden

  removetoken:
    permission: btetoken.remove
    description: Usern Token entfernen

  token:
    description: Zeige aktuelle Donator Token
